spring:
  application:
    name: fraud-detection-engine
    parameters:
      invalid-time:
        grace-period: 30
      high-volume:
        threshold: 5
        time-window: 5

  kafka:
    producer:
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
    streams:
      properties:
        "[default.key.serde]": "org.apache.kafka.common.serialization.Serdes$StringSerde"
        "[default.value.serde]": "org.springframework.kafka.support.serializer.JsonSerde"
        spring.json.trusted.packages: "*"

kafka:
  bootstrap-servers: localhost:9092

application.id: a5a882e8-6b04-49cb-86d1-3787571366e6

server:
  port: 19004
